language: node_js
node_js:
  - "6.11.0"
# Speeds up build time since it doesn't have to install the same packages again.
cache:
  directories:
    - node_modules

install:
  - npm install -g codecov

after_success:
  - codecov --file ./coverage/lcov.info --disable search
